### PR TITLE
Update fabric_mods_install.md (mod to mods)

### PR DESCRIPTION
**Pull request by dribnet**
I believe the mods folder is "mods"

### CODE REVIEW

**Comment by GravermanDev** [comment]
correct it is, though honestly I doubt anyone would notice

**Comment by theblazehen** [comment]
I noticed, got me confused for a moment

**Comment by dribnet** [comment]
maybe i'm the only one dumb enough to actually make a separate `mod` folder and then be confused when nothing loads from there. 

also fwiw: i couldn't get `better-respond` to build the right version, but simply downloading the fabric 1.19 version [from here](https://www.curseforge.com/minecraft/mc-mods/better-respawn/download/3851322) seemed to work fine for me. ymmv.

**Comment by xieleo5** [comment]
Hi, thanks for fixing the typo in the document. Merged!

**Pull request merged**
